////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2013-2015 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (; MStar; Confidential; Information; ) by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
//****************************************************
// MST9U_ADC_Driver
// Excel File version:0.4
// 1/16/2015 11:51
//****************************************************

#ifndef _DRVADCTBL_H_
#define _DRVADCTBL_H_

#define DRV_ADC_REG(reg) ((reg>>16)&0xFF), ((reg>>8)&0xFF), (reg&0xFF)
#define REG_ADC_ADDR_SIZE       3
#define REG_ADC_MASK_SIZE       1
#define REG_ADC_DATA_SIZE       2
typedef enum
{
    ADC_TABLE_INIT_All,
    ADC_TABLE_INIT_NUMS
} ADC_INIT_TYPE;

typedef enum
{
    ADC_TABLE_FreeRunEn_All,
    ADC_TABLE_FreeRunEn_NUMS
} ADC_FreeRunEn_TYPE;

typedef enum
{
    ADC_TABLE_FreeRunDis_All,
    ADC_TABLE_FreeRunDis_NUMS
} ADC_FreeRunDis_TYPE;

typedef enum
{
    ADC_TABLE_PorstEn_All,
    ADC_TABLE_PorstEn_NUMS
} ADC_PorstEn_TYPE;

typedef enum
{
    ADC_TABLE_PorstDis_All,
    ADC_TABLE_PorstDis_NUMS
} ADC_PorstDis_TYPE;

typedef enum
{
    ADC_TABLE_MUX_RGB0_Sync,
    ADC_TABLE_MUX_NUMS
} ADC_MUX_TYPE;

typedef enum
{
    ADC_TABLE_SOURCE_RGB,
    ADC_TABLE_SOURCE_YUV,
    ADC_TABLE_SOURCE_SOG,
    ADC_TABLE_SOURCE_YUV_HV,
    ADC_TABLE_SOURCE_NUMS
} ADC_SOURCE_TYPE;

typedef enum
{
    ADC_TABLE_AdcCal_SW_UG,
    ADC_TABLE_AdcCal_Fix_UG,
    ADC_TABLE_AdcCal_BG_Fix_UG,
    ADC_TABLE_AdcCal_NUMS
} ADC_AdcCal_TYPE;

typedef enum
{
    ADC_TABLE_FREQ_SECTION1,
    ADC_TABLE_FREQ_SECTION2,
    ADC_TABLE_FREQ_SECTION3,
    ADC_TABLE_FREQ_SECTION4,
    ADC_TABLE_FREQ_SECTION5,
    ADC_TABLE_FREQ_SECTION6,
    ADC_TABLE_FREQ_SECTION7,
    ADC_TABLE_FREQ_SECTION8,
    ADC_TABLE_FREQ_SECTION9,
    ADC_TABLE_FREQ_SECTION10,
    ADC_TABLE_FREQ_SECTION11,
    ADC_TABLE_FREQ_SECTION12,
    ADC_TABLE_FREQ_SECTION13,
    ADC_TABLE_FREQ_SECTION14,
    ADC_TABLE_FREQ_SECTION15,
    ADC_TABLE_FREQ_SECTION16,
    ADC_TABLE_FREQ_SECTION17,
    ADC_TABLE_SetMode_NUMS
} ADC_SetMode_TYPE;

typedef enum
{
    ADC_TABLE_PowerDown_NUMS
} ADC_PowerDown_TYPE;

typedef struct
{
    WORD FreqHLimit;
    WORD FreqLLimit;
} ADC_FREQ_RANGE;
#if ENABLE_VGA_INPUT


#ifdef _DRVADC_C_
//****************************************************
// INIT
//****************************************************
const BYTE MST_ADCINIT_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_INIT_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_PMATOP_04_L), 0x06, 0x00, 0x00/*$All*/, },
#if MS_VGA_SOG_EN
 { DRV_ADC_REG(REG_ADC_PMATOP_04_H), 0x86, 0x00, 0x00/*$All*/, },
 { DRV_ADC_REG(REG_ADC_PMATOP_30_L), 0x01, 0x00, 0x00/*All*/, },
#else
 { DRV_ADC_REG(REG_ADC_PMATOP_04_H), 0x86, 0x00, 0x06/*$All*/, },
 { DRV_ADC_REG(REG_ADC_PMATOP_30_L), 0x01, 0x00, 0x01/*All*/, },
#endif
 { DRV_ADC_REG(REG_ADC_PMATOP_5A_L), 0xE0, 0x00, 0x00/*$All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_04_L), 0xE1, 0x00, 0x00/*$All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_04_H), 0x07, 0x00, 0x00/*$All*/, },
#if MS_VGA_SOG_EN
 { DRV_ADC_REG(REG_ADC_ATOP_05_L), 0x0C, 0x00, 0x00/*$All*/, },
#else
 { DRV_ADC_REG(REG_ADC_ATOP_05_L), 0x0C, 0x00, 0x0C/*$All*/, },
#endif
 { DRV_ADC_REG(REG_ADC_ATOP_05_H), 0x09, 0x00, 0x00/*$All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_06_L), 0xFF, 0x00, 0x00/*$All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_06_H), 0xFF, 0x00, 0x00/*$All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_0E_L), 0x01, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_PMATOP_27_L), 0x1F, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_PMATOP_29_L), 0xFF, 0x00, 0x6A/*All*/, },
 { DRV_ADC_REG(REG_ADC_PMATOP_29_H), 0x0C, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_39_H), 0x20, 0x00, 0x20/*All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_7A_H), 0xFF, 0x00, 0x28/*All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_7B_L), 0x2A, 0x00, 0x2A/*All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_19_L), 0x09, 0x00, 0x08/*$All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_30_L), 0x07, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_76_L), 0xF0, 0x00, 0xE0/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_76_H), 0x0F, 0x00, 0x07/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_0D_H), 0x10, 0x00, 0x10/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_07_L), 0x18, 0x00, 0x00/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_07_H), 0xFF, 0x00, 0x04/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_63_L), 0x3F, 0x00, 0x17/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_18_L), 0xFF, 0x00, 0x20/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_18_H), 0x07, 0x00, 0x07/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_19_H), 0x1E, 0x00, 0x04/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_65_L), 0xFF, 0x00, 0xCC/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_65_H), 0xFF, 0x00, 0xCC/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_22_L), 0xFF, 0x00, 0x05/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_22_H), 0x0F, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_23_L), 0xFF, 0x00, 0xD0/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_23_H), 0x1F, 0x00, 0x07/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_24_L), 0xFF, 0x00, 0x60/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_24_H), 0x3F, 0x00, 0x20/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_25_L), 0xFF, 0x00, 0xA0/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_25_H), 0x1F, 0x00, 0x03/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_26_L), 0xFF, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_26_H), 0x3F, 0x00, 0x1C/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_27_L), 0xFF, 0x00, 0x40/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_27_H), 0x3F, 0x00, 0x05/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_28_L), 0xFF, 0x00, 0x4A/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_28_H), 0xFF, 0x00, 0x08/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_29_L), 0xFF, 0x00, 0x10/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_29_H), 0x3F, 0x00, 0x20/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2C_L), 0xFF, 0x00, 0x05/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2C_H), 0x0F, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2D_L), 0xFF, 0x00, 0xD0/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2D_H), 0x1F, 0x00, 0x07/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2E_L), 0xFF, 0x00, 0x60/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2E_H), 0x3F, 0x00, 0x20/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2F_L), 0xFF, 0x00, 0xA0/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2F_H), 0x1F, 0x00, 0x03/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_30_L), 0xFF, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_30_H), 0x3F, 0x00, 0x1C/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_31_L), 0xFF, 0x00, 0x40/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_31_H), 0x3F, 0x00, 0x05/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_32_L), 0xFF, 0x00, 0x4A/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_32_H), 0xFF, 0x00, 0x08/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_33_L), 0xFF, 0x00, 0x10/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_33_H), 0x3F, 0x00, 0x20/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_36_L), 0xFF, 0x00, 0x05/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_36_H), 0x0F, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_37_L), 0xFF, 0x00, 0xD0/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_37_H), 0x1F, 0x00, 0x07/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_38_L), 0xFF, 0x00, 0x60/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_38_H), 0x3F, 0x00, 0x20/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_39_L), 0xFF, 0x00, 0xA0/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_39_H), 0x1F, 0x00, 0x03/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_3A_L), 0xFF, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_3A_H), 0x3F, 0x00, 0x1C/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_3B_L), 0xFF, 0x00, 0x40/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_3B_H), 0x3F, 0x00, 0x05/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_3C_L), 0xFF, 0x00, 0x4A/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_3C_H), 0xFF, 0x00, 0x08/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_3D_L), 0xFF, 0x00, 0x10/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_3D_H), 0x3F, 0x00, 0x20/*$All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_53_L), 0x1F, 0x00, 0x08/*All*/, },
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

//****************************************************
// FreeRunEn
//****************************************************
const BYTE MST_ADCFreeRunEn_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_FreeRunEn_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_DTOP_01_L), 0xFF, 0x00, 0x56/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_01_H), 0xFF, 0x00, 0x66/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_02_L), 0xFF, 0x00, 0x66/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_02_H), 0xFF, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_06_L), 0xFF, 0x00, 0x80/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_06_H), 0xFF, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_09_H), 0x18, 0x00, 0x10/*All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_0C_L), 0x07, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

//****************************************************
// FreeRunDis
//****************************************************
const BYTE MST_ADCFreeRunDis_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_FreeRunDis_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_DTOP_06_L), 0xFF, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_06_H), 0xFF, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_01_L), 0xFF, 0x00, 0x82/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_01_H), 0xFF, 0x00, 0x09/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_02_L), 0xFF, 0x00, 0x05/*All*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_02_H), 0xFF, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

//****************************************************
// PorstEn
//****************************************************
const BYTE MST_ADCPorstEn_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_PorstEn_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_ATOP_0E_L), 0xFE, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_0E_H), 0xFF, 0x00, 0x02/*All*/, },
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

//****************************************************
// PorstDis
//****************************************************
const BYTE MST_ADCPorstDis_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_PorstDis_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_ATOP_0E_L), 0xFE, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_0E_H), 0xFF, 0x00, 0x00/*All*/, },
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

//****************************************************
// MUX
//****************************************************
const BYTE MST_ADCMUX_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_MUX_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_ATOP_01_L), 0x03, 0x00, 0x00/*RGB0_Sync*/, },
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

//****************************************************
// SOURCE
//****************************************************
const BYTE MST_ADCSOURCE_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_SOURCE_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_ATOP_00_L), 0xF7, 0x00, 0x01/*RGB*/,
                                         0x00, 0x01/*YUV*/,
                                         0x00, 0x01/*SOG*/,
                                         0x00, 0x01/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_01_H), 0x43, 0x00, 0x40/*$RGB*/,
                                         0x00, 0x40/*$YUV*/,
                                         0x00, 0x40/*$SOG*/,
                                         0x00, 0x40/*$YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_01_L), 0xF0, 0x00, 0x00/*$RGB*/,
                                         0x00, 0x00/*$YUV*/,
                                         0x00, 0x00/*$SOG*/,
                                         0x00, 0x00/*$YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_03_L), 0x01, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_32_L), 0xFF, 0x00, 0x30/*RGB*/,
                                         0x00, 0x30/*YUV*/,
                                         0x00, 0x30/*SOG*/,
                                         0x00, 0x30/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_07_L), 0x60, 0x00, 0x00/*$RGB*/,
                                         0x00, 0x60/*$YUV*/,
                                         0x00, 0x60/*$SOG*/,
                                         0x00, 0x00/*$YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_12_H), 0x01, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_61_H), 0x10, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_67_H), 0x03, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_21_H), 0x0F, 0x00, 0x01/*RGB*/,
                                         0x00, 0x08/*YUV*/,
                                         0x00, 0x01/*SOG*/,
                                         0x00, 0x08/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_21_L), 0xFF, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2B_H), 0x0F, 0x00, 0x01/*RGB*/,
                                         0x00, 0x01/*YUV*/,
                                         0x00, 0x01/*SOG*/,
                                         0x00, 0x01/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_2B_L), 0xFF, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_35_H), 0x0F, 0x00, 0x01/*RGB*/,
                                         0x00, 0x08/*YUV*/,
                                         0x00, 0x01/*SOG*/,
                                         0x00, 0x08/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_35_L), 0xFF, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_50_H), 0x0F, 0x00, 0x01/*RGB*/,
                                         0x00, 0x08/*YUV*/,
                                         0x00, 0x01/*SOG*/,
                                         0x00, 0x08/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_50_L), 0xFF, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_51_H), 0x3F, 0x01, 0x00/*RGB*/,
                                         0x01, 0x00/*YUV*/,
                                         0x01, 0x00/*SOG*/,
                                         0x01, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_51_L), 0xFF, 0x01, 0x00/*RGB*/,
                                         0x01, 0x00/*YUV*/,
                                         0x01, 0x00/*SOG*/,
                                         0x01, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_52_H), 0x7F, 0x00, 0x00/*$RGB*/,
                                         0x00, 0x08/*$YUV*/,
                                         0x00, 0x00/*$SOG*/,
                                         0x00, 0x08/*$YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_52_L), 0xFF, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_55_H), 0x0F, 0x00, 0x01/*RGB*/,
                                         0x00, 0x01/*YUV*/,
                                         0x00, 0x01/*SOG*/,
                                         0x00, 0x01/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_55_L), 0xFF, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_56_H), 0x3F, 0x01, 0x00/*RGB*/,
                                         0x01, 0x00/*YUV*/,
                                         0x01, 0x00/*SOG*/,
                                         0x01, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_56_L), 0xFF, 0x01, 0x00/*RGB*/,
                                         0x01, 0x00/*YUV*/,
                                         0x01, 0x00/*SOG*/,
                                         0x01, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_57_H), 0x7F, 0x00, 0x00/*$RGB*/,
                                         0x00, 0x01/*$YUV*/,
                                         0x00, 0x00/*$SOG*/,
                                         0x00, 0x01/*$YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_57_L), 0xFF, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_5A_H), 0x0F, 0x00, 0x01/*RGB*/,
                                         0x00, 0x08/*YUV*/,
                                         0x00, 0x01/*SOG*/,
                                         0x00, 0x08/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_5A_L), 0xFF, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_5B_H), 0x3F, 0x01, 0x00/*RGB*/,
                                         0x01, 0x00/*YUV*/,
                                         0x01, 0x00/*SOG*/,
                                         0x01, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_5B_L), 0xFF, 0x01, 0x00/*RGB*/,
                                         0x01, 0x00/*YUV*/,
                                         0x01, 0x00/*SOG*/,
                                         0x01, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_5C_H), 0x7F, 0x00, 0x00/*$RGB*/,
                                         0x00, 0x08/*$YUV*/,
                                         0x00, 0x00/*$SOG*/,
                                         0x00, 0x08/*$YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_5C_L), 0xFF, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_63_L), 0xC0, 0x00, 0xC0/*$RGB*/,
                                         0x00, 0xC0/*$YUV*/,
                                         0x00, 0xC0/*$SOG*/,
                                         0x00, 0xC0/*$YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_63_H), 0x03, 0x00, 0x03/*RGB*/,
                                         0x00, 0x03/*YUV*/,
                                         0x00, 0x03/*SOG*/,
                                         0x00, 0x03/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_68_L), 0x04, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_0D_L), 0xFF, 0x00, 0x01/*RGB*/,
                                         0x00, 0x01/*YUV*/,
                                         0x00, 0x01/*SOG*/,
                                         0x00, 0x01/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_0D_H), 0x0F, 0x00, 0x00/*RGB*/,
                                         0x00, 0x00/*YUV*/,
                                         0x00, 0x00/*SOG*/,
                                         0x00, 0x00/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOP_08_H), 0xFF, 0x00, 0x10/*RGB*/,
                                         0x00, 0x10/*YUV*/,
                                         0x00, 0x10/*SOG*/,
                                         0x00, 0x10/*YUV_HV*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_FE_L), 0xFF, 0x00, 0x05/*RGB*/,
                                         0x00, 0x05/*YUV*/,
                                         0x00, 0x05/*SOG*/,
                                         0x00, 0x05/*YUV_HV*/, },
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

//****************************************************
// AdcCal
//****************************************************
const BYTE MST_ADCAdcCal_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_AdcCal_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_DTOPB_02_H), 0x18, 0x00, 0x08/*SW_UG*/,
                                         0x00, 0x08/*Fix_UG*/,
                                         0x00, 0x08/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_7B_H), 0xE0, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_06_L), 0x01, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_06_H), 0xFF, 0x00, 0x70/*$SW_UG*/,
                                         0x00, 0x70/*$Fix_UG*/,
                                         0x00, 0x70/*$BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_07_L), 0x07, 0x00, 0x07/*SW_UG*/,
                                         0x00, 0x07/*Fix_UG*/,
                                         0x00, 0x07/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_08_L), 0xFF, 0x00, 0x3F/*SW_UG*/,
                                         0x00, 0x3F/*Fix_UG*/,
                                         0x00, 0x3F/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_08_H), 0x0F, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_09_L), 0xFF, 0x00, 0xFF/*SW_UG*/,
                                         0x00, 0xFF/*Fix_UG*/,
                                         0x00, 0xFF/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_0A_L), 0x20, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_0A_H), 0x20, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_0B_L), 0x20, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_04_L), 0x07, 0x00, 0x06/*SW_UG*/,
                                         0x00, 0x06/*Fix_UG*/,
                                         0x00, 0x06/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_02_H), 0x01, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_FE_L), 0xFF, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_04_L), 0x07, 0x00, 0x05/*SW_UG*/,
                                         0x00, 0x05/*Fix_UG*/,
                                         0x00, 0x05/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_02_H), 0x01, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_FE_L), 0xFF, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_04_L), 0x07, 0x00, 0x03/*SW_UG*/,
                                         0x00, 0x03/*Fix_UG*/,
                                         0x00, 0x03/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_02_H), 0x01, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_FE_L), 0xFF, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_3F_L), 0xFF, 0x00, 0x37/*$SW_UG*/,
                                         0x00, 0x37/*$Fix_UG*/,
                                         0x00, 0x37/*$BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_3F_H), 0x8F, 0x00, 0x8C/*$SW_UG*/,
                                         0x00, 0x8C/*$Fix_UG*/,
                                         0x00, 0x8C/*$BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_40_L), 0xFF, 0x00, 0xFF/*SW_UG*/,
                                         0x00, 0xC0/*Fix_UG*/,
                                         0x00, 0xC0/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_40_H), 0x0F, 0x00, 0x07/*SW_UG*/,
                                         0x00, 0x07/*Fix_UG*/,
                                         0x00, 0x07/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_41_L), 0x8F, 0x00, 0x8C/*$SW_UG*/,
                                         0x00, 0x8C/*$Fix_UG*/,
                                         0x00, 0x8C/*$BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_04_L), 0x08, 0x00, 0x08/*SW_UG*/,
                                         0x00, 0x08/*Fix_UG*/,
                                         0x00, 0x08/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_5A_L), 0x01, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_5A_L), 0x10, 0x00, 0x10/*SW_UG*/,
                                         0x00, 0x10/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_02_H), 0x18, 0x00, 0x10/*SW_UG*/,
                                         0x00, 0x10/*Fix_UG*/,
                                         0x00, 0x10/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_02_H), 0x20, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_7B_H), 0xE0, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_12_L), 0x0F, 0x00, 0x0F/*$SW_UG*/,
                                         0x00, 0x0F/*$Fix_UG*/,
                                         0x00, 0x0F/*$BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_13_L), 0xFF, 0x00, 0x3F/*SW_UG*/,
                                         0x00, 0x3F/*Fix_UG*/,
                                         0x00, 0x3F/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_13_H), 0x0F, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_14_L), 0xFF, 0x00, 0xFF/*SW_UG*/,
                                         0x00, 0xFF/*Fix_UG*/,
                                         0x00, 0xFF/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_1F_L), 0x1F, 0x00, 0x0F/*$SW_UG*/,
                                         0x00, 0x0F/*$Fix_UG*/,
                                         0x00, 0x0F/*$BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_20_L), 0xFF, 0x00, 0x3F/*SW_UG*/,
                                         0x00, 0x3F/*Fix_UG*/,
                                         0x00, 0x3F/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_20_H), 0x0F, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_21_L), 0xFF, 0x00, 0xFF/*SW_UG*/,
                                         0x00, 0xFF/*Fix_UG*/,
                                         0x00, 0xFF/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_21_H), 0xFF, 0x00, 0xFF/*SW_UG*/,
                                         0x00, 0xFF/*Fix_UG*/,
                                         0x00, 0xFF/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_04_L), 0x07, 0x00, 0x06/*SW_UG*/,
                                         0x00, 0x06/*Fix_UG*/,
                                         0x00, 0x06/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_02_H), 0x01, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_FE_L), 0xFF, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_04_L), 0x07, 0x00, 0x05/*SW_UG*/,
                                         0x00, 0x05/*Fix_UG*/,
                                         0x00, 0x05/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_02_H), 0x01, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_FE_L), 0xFF, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_04_L), 0x07, 0x00, 0x03/*SW_UG*/,
                                         0x00, 0x03/*Fix_UG*/,
                                         0x00, 0x03/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_02_H), 0x01, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_FE_L), 0xFF, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_39_H), 0x20, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_3C_H), 0x20, 0x00, 0x00/*SW_UG*/,
                                         0x00, 0x00/*Fix_UG*/,
                                         0x00, 0x00/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_FE_L), 0xFF, 0x00, 0x01/*SW_UG*/,
                                         0x00, 0x01/*Fix_UG*/,
                                         0x00, 0x01/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_39_H), 0x20, 0x00, 0x20/*SW_UG*/,
                                         0x00, 0x20/*Fix_UG*/,
                                         0x00, 0x20/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_ATOP_3C_H), 0x20, 0x00, 0x20/*SW_UG*/,
                                         0x00, 0x20/*Fix_UG*/,
                                         0x00, 0x20/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_ADC_DTOPB_FE_L), 0xFF, 0x00, 0x0A/*SW_UG*/,
                                         0x00, 0x0A/*Fix_UG*/,
                                         0x00, 0x0A/*BG_Fix_UG*/, },
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

//****************************************************
// SetMode
//****************************************************
ADC_FREQ_RANGE MST_ADC_FreqRange_TBL[]=
{
    //H-Limit,  L-Limit
    { 0x1000,   0x012C},/*ADC_FREQ_SECTION1*/
    { 0x012C,   0x00FA},/*ADC_FREQ_SECTION2*/
    { 0x00FA,   0x00C8},/*ADC_FREQ_SECTION3*/
    { 0x00C8,   0x00B4},/*ADC_FREQ_SECTION4*/
    { 0x00B4,   0x00A0},/*ADC_FREQ_SECTION5*/
    { 0x00A0,   0x008C},/*ADC_FREQ_SECTION6*/
    { 0x008C,   0x0078},/*ADC_FREQ_SECTION7*/
    { 0x0078,   0x0064},/*ADC_FREQ_SECTION8*/
    { 0x0064,   0x0050},/*ADC_FREQ_SECTION9*/
    { 0x0050,   0x0046},/*ADC_FREQ_SECTION10*/
    { 0x0046,   0x003C},/*ADC_FREQ_SECTION11*/
    { 0x003C,   0x002D},/*ADC_FREQ_SECTION12*/
    { 0x002D,   0x0028},/*ADC_FREQ_SECTION13*/
    { 0x0028,   0x001E},/*ADC_FREQ_SECTION14*/
    { 0x001E,   0x0014},/*ADC_FREQ_SECTION15*/
    { 0x0014,   0x000F},/*ADC_FREQ_SECTION16*/
    { 0x000F,   0x0005},/*ADC_FREQ_SECTION17*/
};

const BYTE MST_ADCSetModeYUV_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_SetMode_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_ATOP_34_L), 0x0F, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x05/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x07/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x09/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x0D/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x0E/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_34_L), 0xF0, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x50/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x60/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x70/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x90/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0xD0/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0xE0/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_34_H), 0x0F, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x05/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x07/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x09/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x0D/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x0E/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_34_H), 0xF0, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x50/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x60/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x70/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x90/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0xD0/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0xE0/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_35_L), 0x0F, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x05/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x07/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x09/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x0D/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x0E/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_35_L), 0xF0, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x50/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x60/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x70/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x90/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0xD0/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0xE0/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_DTOP_17_H), 0x0F, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_DTOP_17_L), 0xFF, 0x00, 0x45/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x45/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_DTOP_18_L), 0xFF, 0x00, 0x80/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_DTOP_19_H), 0x60, 0x00, 0x40/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_0D_L), 0x10, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_0C_L), 0x07, 0x00, 0x01/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_09_H), 0x18, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x18/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x18/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x18/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_0A_L), 0x04, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_61_H), 0x60, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_09_H), 0x07, 0x00, 0x02/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

const BYTE MST_ADCSetModeRGB_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_SetMode_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_ATOP_34_L), 0x0F, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x03/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x05/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x07/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x09/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x0D/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_34_L), 0xF0, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x50/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x60/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x70/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x90/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0xD0/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_34_H), 0x0F, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x03/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x05/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x07/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x09/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x0D/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_34_H), 0xF0, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x50/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x60/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x70/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x90/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0xD0/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_35_L), 0x0F, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x03/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x05/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x07/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x09/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x0D/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_35_L), 0xF0, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x50/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x60/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x70/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x90/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0xD0/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_DTOP_17_H), 0x0F, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_DTOP_17_L), 0xFF, 0x00, 0x30/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_DTOP_18_L), 0xFF, 0x00, 0x80/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_DTOP_19_H), 0x60, 0x00, 0x40/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_0D_L), 0x10, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_0C_L), 0x07, 0x00, 0x01/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_09_H), 0x18, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x18/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x18/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x18/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_0A_L), 0x04, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_61_H), 0x60, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_09_H), 0x07, 0x00, 0x02/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

const BYTE MST_ADCSetModeYUV_Y_TBL[][REG_ADC_ADDR_SIZE+REG_ADC_MASK_SIZE+ADC_TABLE_SetMode_NUMS*REG_ADC_DATA_SIZE]=
{                 // Reg           Mask Ignore Value
 { DRV_ADC_REG(REG_ADC_ATOP_34_H), 0x0F, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x01/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x02/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x03/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x04/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x05/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x06/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x07/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x08/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x09/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0x0A/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0x0B/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0x0C/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0x0D/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_ADC_ATOP_34_H), 0xF0, 0x00, 0x00/*ADC_TABLE_FREQ_SECTION1*/,
                                         0x00, 0x00/*ADC_TABLE_FREQ_SECTION2*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION3*/,
                                         0x00, 0x10/*ADC_TABLE_FREQ_SECTION4*/,
                                         0x00, 0x20/*ADC_TABLE_FREQ_SECTION5*/,
                                         0x00, 0x30/*ADC_TABLE_FREQ_SECTION6*/,
                                         0x00, 0x40/*ADC_TABLE_FREQ_SECTION7*/,
                                         0x00, 0x50/*ADC_TABLE_FREQ_SECTION8*/,
                                         0x00, 0x60/*ADC_TABLE_FREQ_SECTION9*/,
                                         0x00, 0x70/*ADC_TABLE_FREQ_SECTION10*/,
                                         0x00, 0x80/*ADC_TABLE_FREQ_SECTION11*/,
                                         0x00, 0x90/*ADC_TABLE_FREQ_SECTION12*/,
                                         0x00, 0xA0/*ADC_TABLE_FREQ_SECTION13*/,
                                         0x00, 0xB0/*ADC_TABLE_FREQ_SECTION14*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION15*/,
                                         0x00, 0xC0/*ADC_TABLE_FREQ_SECTION16*/,
                                         0x00, 0xD0/*ADC_TABLE_FREQ_SECTION17*/,},
 { DRV_ADC_REG(REG_TABLE_END), 0x00, 0x00, 0x00 }
};

//****************************************************
// PowerDown
//****************************************************
#endif // _MSDAC_C_
#endif // ENABLE_VGA_INPUT
#endif // _DRVADCTBL_H_
