#ifndef MHAL_HDMIRX_STRUCH_H
#define MHAL_HDMIRX_STRUCH_H

typedef enum
{
    HDMI_TIMING_DET_DTOPDEC_DC_AUTO = 0,
    HDMI_TIMING_DET_DTOPDEC_HDCP_AUTO,
    HDMI_TIMING_DET_DTOPDEC_DC_1P,
    HDMI_TIMING_DET_DTOPDEC_DC_8P,
    HDMI_TIMING_DET_DTOPDEC_HDCP_1P,
    HDMI_TIMING_DET_DTOPDEC_HDCP_8P,
}EN_HDMI_TIMING_DETECT_PATH_DTOPDEC;

typedef enum
{
    HDMI_TIMING_DET_DTOPDEP_AUTO = 0,  // dither_1p(tmds) or rcvtop(frl)
    HDMI_TIMING_DET_DTOPDEP_DITHER_1P,
    HDMI_TIMING_DET_DTOPDEP_RCVTOP,
    HDMI_TIMING_DET_DTOPDEP_SC,
}EN_HDMI_TIMING_DETECT_PATH_DTOPDEP;

typedef enum
{
    HDMI_TIMING_DET_DC_1P = 0,
    HDMI_TIMING_DET_HDCP_1P,
    HDMI_TIMING_DET_DITHER_1P,
    HDMI_TIMING_DET_DC_8P,
    HDMI_TIMING_DET_HDCP_8P,
    HDMI_TIMING_DET_RCV_TOP,
    HDMI_TIMING_DET_SC,
}EN_HDMI_TIMING_DETECT_PATH;


typedef enum
{
    HDMI_TIMING_CHG_DTOPDEC_DE_UNSTABLE = 0,
    HDMI_TIMING_CHG_DTOPDEC_MODECHG_8P,
    HDMI_TIMING_CHG_DTOPDEC_DCFIFO_UNF,
    HDMI_TIMING_CHG_DTOPDEC_DCFIFO_OVF,
    HDMI_TIMING_CHG_DTOPDEC_X74_ENC_EN_RAISE,
    HDMI_TIMING_CHG_DTOPDEC_X74_ENC_EN_FALL,
    HDMI_TIMING_CHG_DTOPDEC_VS_ACTIVE_EDGE,
    HDMI_TIMING_CHG_DTOPDEC_VS_1P,
    HDMI_TIMING_CHG_DTOPDEC_HDMI_MODE_CHG,
    HDMI_TIMING_CHG_DTOPDEC_8P_DE_CHG,
    HDMI_TIMING_CHG_DTOPDEC_FRL_DECODER_I_MODE_CHG, // 10
    HDMI_TIMING_CHG_DTOPDEC_HDCP_VS_OR, // 11

    HDMI_TIMING_CHG_DTOPDEC_HS_POL_CHG = 16,
    HDMI_TIMING_CHG_DTOPDEC_VS_POL_CHG,
    HDMI_TIMING_CHG_DTOPDEC_HSYNC_CHG,
    HDMI_TIMING_CHG_DTOPDEC_HFRONT_CHG,
    HDMI_TIMING_CHG_DTOPDEC_HDE_CHG,
    HDMI_TIMING_CHG_DTOPDEC_HTT_CHG,
    HDMI_TIMING_CHG_DTOPDEC_VBACK_CHG,
    HDMI_TIMING_CHG_DTOPDEC_VSYNC_CHG_CHG,
    HDMI_TIMING_CHG_DTOPDEC_VFRONT_CHG,
    HDMI_TIMING_CHG_DTOPDEC_VDE_CHG,
    HDMI_TIMING_CHG_DTOPDEC_VTT_CHG, // 26

    HDMI_TIMING_CHG_DTOPDEC_CLK_DEC_MISC_0_DE_OVF = 28,
    HDMI_TIMING_CHG_DTOPDEC_CLK_DEC_MISC_0_UNSTABLE,
    HDMI_TIMING_CHG_DTOPDEC_CLK_DEC_MISC_1_DE_OVF,
    HDMI_TIMING_CHG_DTOPDEC_CLK_DEC_MISC_1_UNSTABLE, // 31
}EN_HDMI_TIMING_CHANGE_STATUS;

typedef enum
{
    HDMI_TIMING_CHG_DTOPDEP_HS_POL_CHG = 0,
    HDMI_TIMING_CHG_DTOPDEP_VS_POL_CHG,
    HDMI_TIMING_CHG_DTOPDEP_HSYNC_CHG,
    HDMI_TIMING_CHG_DTOPDEP_HFRONT_CHG,
    HDMI_TIMING_CHG_DTOPDEP_HDE_CHG,
    HDMI_TIMING_CHG_DTOPDEP_HTT_CHG,
    HDMI_TIMING_CHG_DTOPDEP_VBACK_CHG,
    HDMI_TIMING_CHG_DTOPDEP_VSYNC_CHG_CHG,
    HDMI_TIMING_CHG_DTOPDEP_VFRONT_CHG,
    HDMI_TIMING_CHG_DTOPDEP_VDE_CHG,
    HDMI_TIMING_CHG_DTOPDEP_VTT_CHG,  // 10

    HDMI_TIMING_CHG_DTOPDEP_CRC_R_DIFF = 12,
    HDMI_TIMING_CHG_DTOPDEP_CRC_G_DIFF,
    HDMI_TIMING_CHG_DTOPDEP_CRC_B_DIFF,

    HDMI_TIMING_CHG_DTOPDEP_CLK_DEC_MISC_0_DE_OVF = 16,
    HDMI_TIMING_CHG_DTOPDEP_CLK_DEC_MISC_0_UNSTABLE,
    HDMI_TIMING_CHG_DTOPDEP_CLK_DEC_MISC_1_DE_OVF,
    HDMI_TIMING_CHG_DTOPDEP_CLK_DEC_MISC_1_UNSTABLE, // 19
}EN_HDMI_TIMING_CHANGE_STATUS_DTOPDEP;

typedef enum
{
    HDMI_TIMING_CHG_DTOPMISC_HS_POL_CHG = 0,
    HDMI_TIMING_CHG_DTOPMISC_VS_POL_CHG,
    HDMI_TIMING_CHG_DTOPMISC_HSYNC_CHG,
    HDMI_TIMING_CHG_DTOPMISC_HFRONT_CHG,
    HDMI_TIMING_CHG_DTOPMISC_HDE_CHG,
    HDMI_TIMING_CHG_DTOPMISC_HTT_CHG,
    HDMI_TIMING_CHG_DTOPMISC_VBACK_CHG,
    HDMI_TIMING_CHG_DTOPMISC_VSYNC_CHG_CHG,
    HDMI_TIMING_CHG_DTOPMISC_VFRONT_CHG,
    HDMI_TIMING_CHG_DTOPMISC_VDE_CHG,
    HDMI_TIMING_CHG_DTOPMISC_VTT_CHG, // 10
    HDMI_TIMING_CHG_DTOPMISC_AUDS0,
    HDMI_TIMING_CHG_DTOPMISC_AUDS1,
    HDMI_TIMING_CHG_DTOPMISC_RXEARCTX, // 13
}EN_HDMI_TIMING_CHANGE_STATUS_DTOPMISC;

typedef enum
{
    HDMI_RST_FRLDEC_DETECT = 0,
    HDMI_RST_FRLDEC_DEPACKER,
    HDMI_RST_FRLDEC_SRAM,
    HDMI_RST_FRLDEC_TIMING,
    HDMI_RST_FRLDEC_ALL = 7,
}EN_HDMI_SWRST_FRLDEC;

typedef enum
{
    HDMI_RST_DTOPDEC_DEC = 0,
    HDMI_RST_DTOPDEC_HDCP,
    HDMI_RST_DTOPDEC_DC,
    HDMI_RST_DTOPDEC_PKT,
    HDMI_RST_DTOPDEC_PWS,
    HDMI_RST_DTOPDEC_TIMING_DET = 6,
    HDMI_RST_DTOPDEC_CLK_DET,
    HDMI_RST_DTOPDEC_ALL = 15,
}EN_HDMI_SWRST_DTOPDEC;


typedef enum
{
    HDMI_RST_DTOPDEP_422 = 0,
    HDMI_RST_DTOPDEP_DITHER,
    HDMI_RST_DTOPDEP_PKT,
    HDMI_RST_DTOPDEP_PKTQ,
    HDMI_RST_DTOPDEP_VIDEOOUT,
    HDMI_RST_DTOPDEP_TIMING_DET = 6,
    HDMI_RST_DTOPDEP_CLK_DET,
    HDMI_RST_DTOPDEP_CRC
}EN_HDMI_SWRST_DTOPDEP;

typedef enum
{
    HDMI_RST_DTOPMISC_TS_S0 = 0,
    HDMI_RST_DTOPMISC_TS_S1,
    HDMI_RST_DTOPMISC_AUDIO_S0 = 10,
    HDMI_RST_DTOPMISC_AUDIO_S1,
    HDMI_RST_DTOPMISC_HDCPKEY,
    HDMI_RST_DTOPMISC_TIMING_DET,
}EN_HDMI_SWRST_DTOPMISC;


typedef enum
{
    HDMI_RST_INNERMISC_DVI2MIU_S0 = 0,
    HDMI_RST_INNERMISC_DVI2MIU_S1,
    HDMI_RST_INNERMISC_TIMER = 4,
    HDMI_RST_INNERMISC_CLK_DET = 7,
    HDMI_RST_INNERMISC_DSCD,
    HDMI_RST_INNERMISC_DSCD_DST,
    HDMI_RST_INNERMISC_DSCD_SRC,
    HDMI_RST_INNERMISC_PORT_SEL_CDC = 12,
}EN_HDMI_SWRST_INNERMISC;


typedef enum
{
    HDMI_RST_RCVTOP_DSCD_FEED = 0,
    HDMI_RST_RCVTOP_DSCD_RCV,
    HDMI_RST_RCVTOP_PLL_TOP,
    HDMI_RST_RCVTOP_RCV_TOP_SW = 5,
    HDMI_RST_RCVTOP_RCV_TGEN,
    HDMI_RST_RCVTOP_SRAM_RST = 8,
}EN_HDMI_SWRST_RCVTOP;

typedef enum
{
    E_CLK_MUX_TIMING_DET_DTOP_DEC,
    E_CLK_MUX_TIMING_DET_DTOP_DEP,
    E_CLK_MUX_TIMING_DET_DTOPMISC,
    E_CLK_MUX_AUDIO_S0,
    E_CLK_MUX_AUDIO_S1,
    E_CLK_MUX_DVI2MIU_S0,
    E_CLK_MUX_DVI2MIU_S1,
    E_CLK_MUX_DVI2MIU_S2,
    E_CLK_MUX_DSC,
    E_CLK_MUX_TMDS_FRL,
}EN_HDMI_CLK_MUX_SEL;

typedef enum
{
    E_DSC_FSM_NONE,
    E_DSC_FSM_HV_REGEN,
    E_DSC_FSM_DSC_CONFIG,
    E_DSC_FSM_REGEN,
}EN_HDMI_DSC_FSM;

typedef enum
{
    HDMI_EMP_SW_RST = 0,
}EN_HDMI_SWRST_EMP;

typedef enum
{
    E_EMP_VED_MORE_PKT = 0,
    E_EMP_VRR_MORE_PKT,
    E_EMP_HDR_MORE_PKT,
    E_EMP_DSC_MORE_PKT,
    E_EMP_VED_NOT_EVERY_MTW,
    E_EMP_VRR_NOT_EVERY_MTW,
    E_EMP_HDR_NOT_EVERY_MTW,
    E_EMP_DSC_NOT_EVERY_MTW,
    E_EMP_VED_ON_NON_FAPA,
    E_EMP_VRR_ON_NON_FAPA,
    E_EMP_HDR_ON_NON_FAPA = 10,
    E_EMP_DSC_ON_NON_FAPA,
    E_EMP_DSC_SEQ_WRONG,
    E_EMP_VED_INCOMPLETE_PKT,
    E_EMP_VRR_INCOMPLETE_PKT,
    E_EMP_HDR_INCOMPLETE_PKT,
    E_EMP_DSC_INCOMPLETE_PKT,
    E_EMP_DSC_LAST_EVT,
    E_EMP_VED_FIRST_EVT,
    E_EMP_VRR_FIRST_EVT,
    E_EMP_HDR_FIRST_EVT = 20,
    E_EMP_DSC_FIRST_EVT,
    E_EMP_PKT_DIFF,
    E_EMP_PKT_RECEIVED,
    E_EMP_DSC_PKT_DIFF,
    E_EMP_VRR_CHG_PULSE,
    E_EMP_DSC_CHG_PULSE,
    E_EMP_MTW_PULSE,
    E_EMP_VSYNC_AHEAD,
    E_EMP_VDE_END_TMDS_P,
    E_EMP_HDR_SINGLE_DSF_EVT,
    E_EMP_DSC_SINGLE_DSF_EVT = 31,
}EN_HDMI_EMP_EVT;

typedef enum
{
    E_SIG_TMDS,
    E_SIG_FRL,
    E_SIG_CR_NO_LOCK,
}EN_HDMI_SIGNAL_TYPE;

typedef enum
{
    HDMI_RST_FRLDECODER_TYPE_DETECT = 0,
    HDMI_RST_FRLDECODER_DEPACKER,
    HDMI_RST_FRLDECODER_SRAM,
    HDMI_RST_FRLDECODER_TIMING_DETECT,
    HDMI_RST_FRLDECODER_RSERVED,
    HDMI_RST_FRLDECODER = 7,
}EN_HDMI_SWRST_FRLDECODER;

typedef enum
{
    E_REGEN_INIT,
    E_REGEN_CONFIG,
    E_REGEN_DONE,
}EN_HDMI_REGEN_FSM;

typedef struct
{
    MS_U8 u8_bpc;     // pps3[7:4]
    MS_U8 u8_linebuf_depth; // pps[3:0]
    MS_U16 u8_convert_rgb; // pps4[4]
    MS_U16 u16_bpp; // bpp_real = u16_bpp >> 4  // pps4[1:0]<<8|pps5
    MS_U16 u16_pic_height;  // pps6<<8|pps7
    MS_U16 u16_pic_width;  // pps8<<8|pps9
    MS_U16 u16_slice_height; // pps10<<8|pps11
    MS_U16 u16_slice_width; // pps12<<8|pps13
    MS_U16 u16_chunkbytes; // pps14<<8|pps15
    MS_U16 u16_initial_dec_delay;  // pps18<<8|pps19
    MS_U8 u8_native_422;  // pps88[0]
    MS_U8 u8_native_420; // pps[1]
    MS_U16 u16_hfront; // pps129<<8|pps128
    MS_U16 u16_hsync; // pps131<<8|pps130
    MS_U16 u16_hback; // pps133<<8|pps132
    MS_U16 u16_hactivebytes; // pps135<<8|pps134
    MS_U8  u8_slice_num;
// clk
    MS_U32 u32_dsc_clk;  // 1 engine
    MS_U32 u32_pixel_clk;  // 1p
    MS_U8 u8_dsc_n;   // 3
    MS_U8 u8_pixel_n;  // 8
    MS_U8 u8_dsc_420_2_444;  // dependent
// reg fill
    MS_U16 u16_reg_entropy_shf_blk_slice;
    MS_U16 u16_reg_entropy_shf_blk;
    MS_U16 u16_reg_ini_dec_line_delay;
    MS_U16 u16_dsc_420_h_factor;
}ST_HDMI_DSC_INFO;

#endif
